# Generated by Django 2.2.1 on 2020-06-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='AccountTypeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='AddressID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='AffiliationID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='allowableservice',
            name='AlowableServiceID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='career',
            name='CareerID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='career',
            name='amateurBouts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='amateurWins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousAmateurBouts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousAmateurCombatSportInvolvement',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousAmateurKOs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousAmateurTKOs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousAmateurWins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousBoutsOutofCountry',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousCombatSportInvolvementInOtherCountry',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousProfessionalCombatSportInvolvement',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousWinsOutofCountry',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousYearsOutofCountry',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='professionalBouts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='professionalWins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='professionalYears',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='MatchID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='numberOfRounds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='wentToFinalRound',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='MatchRoundID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='blueBoxerScore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='redBoxerScore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='roundNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicalcert',
            name='MedicalCertID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalcert',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='NonBoxerInfoID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='coachLevel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='judgeOnlyPreference',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='nccpNum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='officialLevel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='policeRecordsCheckExpiry',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='policeRecordsCheckPerformed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='OrganizationID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='PersonID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='emailAddress',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastLoginDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='PersonInfoID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='businessPhone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='cellPhone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='dateofBirth',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='fax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='homePhone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='RoleID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='SeriesID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='ServiceID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceenrollment',
            name='ServiceEnrollmentID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceenrollment',
            name='endDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceenrollment',
            name='startDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='ShowID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signature',
            name='SignatureID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signedwaiver',
            name='SignedWaiverID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signedwaiver',
            name='signatureDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signedwaiver',
            name='waiverID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='WaiverID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='waiverrequirement',
            name='WaiverRequirementID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='waiverrequirement',
            name='annualRenewalRequired',
            field=models.BooleanField(),
        ),
    ]
