# Generated by Django 2.2.1 on 2020-06-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0002_auto_20200624_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcert',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='policeRecordsCheckExpiry',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastLoginDateTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='dateofBirth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceenrollment',
            name='endDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceenrollment',
            name='startDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='signedwaiver',
            name='signatureDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
