# Generated by Django 3.0.8 on 2020-07-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0003_auto_20200624_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lastLoginDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
