# Generated by Django 3.0.8 on 2020-07-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0006_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='accountTypeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Person_Account_Type', to='FightScheduler.AccountType', verbose_name='Person Account Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='statusCode',
            field=models.ForeignKey(default='NEW', on_delete=django.db.models.deletion.CASCADE, related_name='Person_System_Status', to='FightScheduler.StatusCode', verbose_name='Person System Status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
