# Generated by Django 3.0.8 on 2020-07-10 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FightScheduler', '0007_auto_20200709_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='PersonID',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='surname',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User_ID_for_Personal_Information', to=settings.AUTH_USER_MODEL, verbose_name='User ID for Personal Information'),
            preserve_default=False,
        ),
    ]
