# Generated by Django 3.0.8 on 2020-07-10 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FightScheduler', '0008_auto_20200710_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='userID',
            new_name='UserID',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='PersonID',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='affiliatedPersonID',
        ),
        migrations.RemoveField(
            model_name='career',
            name='PersonID',
        ),
        migrations.RemoveField(
            model_name='match',
            name='blueBoxerPersonID',
        ),
        migrations.RemoveField(
            model_name='match',
            name='cornerJudge1PersonID',
        ),
        migrations.RemoveField(
            model_name='match',
            name='cornerJudge2PersonID',
        ),
        migrations.RemoveField(
            model_name='match',
            name='cornerJudge3PersonID',
        ),
        migrations.RemoveField(
            model_name='match',
            name='cornerJudge4PersonID',
        ),
        migrations.RemoveField(
            model_name='match',
            name='redBoxerPersonID',
        ),
        migrations.RemoveField(
            model_name='match',
            name='refereePersonID',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winnerPersonID',
        ),
        migrations.RemoveField(
            model_name='medicalcert',
            name='PersonID',
        ),
        migrations.RemoveField(
            model_name='nonboxerinfo',
            name='PersonID',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='clubCoachPersonID',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='clubOwnerPersonID',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='clubPresidentPersonID',
        ),
        migrations.RemoveField(
            model_name='serviceenrollment',
            name='personID',
        ),
        migrations.RemoveField(
            model_name='signedwaiver',
            name='signatoryPersonID',
        ),
        migrations.RemoveField(
            model_name='signedwaiver',
            name='waiverFormPersonID',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User_Affiliation_to_Organization', to=settings.AUTH_USER_MODEL, verbose_name='User Affiliation to Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliation',
            name='affiliatedUserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User_Affiliated_to_Other_User_in_Organization', to=settings.AUTH_USER_MODEL, verbose_name='User Affiliated to Other User in Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User_ID_for_Career_Info', to=settings.AUTH_USER_MODEL, verbose_name='User ID for Career Info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='blueBoxerUserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Blue_Corner_Boxer', to=settings.AUTH_USER_MODEL, verbose_name='Blue Corner Boxer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='cornerJudge1UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Corner_Judge_1_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 1 User ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='cornerJudge2UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Corner_Judge_2_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 2 User ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='cornerJudge3UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Corner_Judge_3_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 3 User ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='cornerJudge4UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Corner_Judge_4_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 4 User ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='redBoxerUserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Red_Corner_Boxer', to=settings.AUTH_USER_MODEL, verbose_name='Red Corner Boxer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='refereeUserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Referee_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Referee User ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='winnerUserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Winning_Boxer_UserID', to=settings.AUTH_USER_MODEL, verbose_name='Winning Boxer UserID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalcert',
            name='UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Medical_Cert_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Medical Cert User ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonboxerinfo',
            name='UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User_ID_for_Additional_Non_Boxer_Info', to=settings.AUTH_USER_MODEL, verbose_name='User ID for Additional Non Boxer Info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='clubCoachUserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Club_Coach_User', to=settings.AUTH_USER_MODEL, verbose_name='Club Coach User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='clubOwnerUserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Club_Owner_User', to=settings.AUTH_USER_MODEL, verbose_name='Club Owner User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='clubPresidentUserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='President_User', to=settings.AUTH_USER_MODEL, verbose_name='President User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceenrollment',
            name='UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Enrolled_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Enrolled User ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signedwaiver',
            name='signatoryUserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Signatory_on_Behalf_Of', to=settings.AUTH_USER_MODEL, verbose_name='Signatory on Behalf Of'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signedwaiver',
            name='waiverFormUserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Waiver_Form_User', to=settings.AUTH_USER_MODEL, verbose_name='Waiver Form User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='currentWeight',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='match',
            name='cornerJudge1Ruling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Corner_Judge_1_Winner_Pick_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 1 Winner Pick User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cornerJudge2Ruling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Corner_Judge_2_Winner_Pick_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 2 Winner Pick User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cornerJudge3Ruling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Corner_Judge_3_Winner_Pick_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 3 Winner Pick User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cornerJudge4Ruling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Corner_Judge_4_Winner_Pick_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 4 Winner Pick User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='refereeRuling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Referee_Winner_Pick_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Referee Winner Pick User ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='accountTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person_Account_Type', to='FightScheduler.AccountType', verbose_name='Person Account Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='statusCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person_System_Status', to='FightScheduler.StatusCode', verbose_name='Person System Status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='addressID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address_of_User', to='FightScheduler.Address', verbose_name='Address of User'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
