# Generated by Django 3.0.8 on 2020-07-16 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FightScheduler', '0009_auto_20200710_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='clubCoachUserID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Club_Coach_User', to=settings.AUTH_USER_MODEL, verbose_name='Club Coach User'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='clubOwnerUserID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Club_Owner_User', to=settings.AUTH_USER_MODEL, verbose_name='Club Owner User'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='clubPresidentUserID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='President_User', to=settings.AUTH_USER_MODEL, verbose_name='President User'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organizationName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
