# Generated by Django 3.0.8 on 2020-07-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0010_auto_20200716_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='businessPhone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='cellPhone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='fax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='homePhone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='phoneExtension',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
