# Generated by Django 3.0.8 on 2020-07-17 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FightScheduler', '0011_auto_20200716_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='AccountTypeID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='AddressID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='AffiliationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='allowableservice',
            name='AlowableServiceID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='career',
            name='CareerID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='career',
            name='UserID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_ID_for_Career_Info', to=settings.AUTH_USER_MODEL, verbose_name='User ID for Career Info'),
        ),
        migrations.AlterField(
            model_name='match',
            name='MatchID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='MatchRoundID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalcert',
            name='MedicalCertID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='NonBoxerInfoID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='OrganizationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='PersonID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='PersonInfoID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='UserID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_ID_for_Personal_Information', to=settings.AUTH_USER_MODEL, verbose_name='User ID for Personal Information'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='addressID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Address_of_User', to='FightScheduler.Address', verbose_name='Address of User'),
        ),
        migrations.AlterField(
            model_name='role',
            name='RoleID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='SeriesID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='ServiceID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceenrollment',
            name='ServiceEnrollmentID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='ShowID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signature',
            name='SignatureID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signedwaiver',
            name='SignedWaiverID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='WaiverID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='waiverrequirement',
            name='WaiverRequirementID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
