# Generated by Django 3.0.8 on 2020-07-18 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FightScheduler', '0012_auto_20200717_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='RoleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Role_ID', to='FightScheduler.Role', verbose_name='Role ID'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='affiliatedOrganizationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Affiliated_Organiation', to='FightScheduler.Organization', verbose_name='Affiliated Organiation'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='UserID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='User_ID_for_Personal_Information', to=settings.AUTH_USER_MODEL, verbose_name='User ID for Personal Information'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='addressID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Address_of_User', to='FightScheduler.Address', verbose_name='Address of User'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='clubName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Club_of_User', to='FightScheduler.Organization', verbose_name='Club of the User'),
        ),
    ]
