# Generated by Django 3.0.8 on 2020-07-18 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0013_auto_20200717_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='clubName',
            new_name='organizationID',
        ),
    ]
