# Generated by Django 2.2.1 on 2020-07-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0014_auto_20200717_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='amateurBouts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='amateurWins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='currentWeight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousAmateurBouts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousAmateurCombatSportInvolvement',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousAmateurKOs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousAmateurTKOs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousAmateurWins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousBoutsOutofCountry',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousCombatSportInvolvementInOtherCountry',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousProfessionalCombatSportInvolvement',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousWinsOutofCountry',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousYearsOutofCountry',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='professionalBouts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='professionalWins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='professionalYears',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='dateofBirth',
            field=models.DateField(null=True),
        ),
    ]
