# Generated by Django 3.0.8 on 2020-07-20 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FightScheduler', '0015_auto_20200719_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('AccountInfoID', models.AutoField(primary_key=True, serialize=False)),
                ('registrationStage', models.CharField(max_length=15)),
                ('boxerType', models.CharField(choices=[('AD', 'Adult Boxer'), ('JR', 'Junior Boxer'), ('NO', 'Not a Boxer')], default='AD', max_length=2)),
                ('isCoach', models.BooleanField(default=False)),
                ('isOwner', models.BooleanField(default=False)),
                ('isOfficial', models.BooleanField(default=False)),
                ('isBoxingOntarioAdmin', models.BooleanField(default=False)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Account_username', to=settings.AUTH_USER_MODEL, verbose_name='Account username')),
            ],
        ),
    ]
