# Generated by Django 3.0.8 on 2020-07-20 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0016_accountinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='registrationStage',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='careerID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Career_ID', to='FightScheduler.Career', verbose_name='Career ID'),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='otherInfoID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Other_Info_ID', to='FightScheduler.Career', verbose_name='Other Info ID'),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='personalInfoID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Personal_Information_ID', to='FightScheduler.PersonalInformation', verbose_name='Personal Information ID'),
        ),
    ]
