# Generated by Django 3.0.8 on 2020-07-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0017_auto_20200720_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='careerID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='otherInfoID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='personalInfoID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
