# Generated by Django 3.0.8 on 2020-07-22 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FightScheduler', '0018_auto_20200720_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='RoleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Role_ID', to='FightScheduler.Role', verbose_name='Role ID'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_Affiliation_to_Organization', to=settings.AUTH_USER_MODEL, verbose_name='User Affiliation to Organization'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='affiliatedOrganizationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Affiliated_Organiation', to='FightScheduler.Organization', verbose_name='Affiliated Organiation'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='affiliatedUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_Affiliated_to_Other_User_in_Organization', to=settings.AUTH_USER_MODEL, verbose_name='User Affiliated to Other User in Organization'),
        ),
        migrations.AlterField(
            model_name='allowableservice',
            name='RoleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Role_Associated_to_Allowed_Service', to='FightScheduler.Role', verbose_name='Role Associated to Allowed Service'),
        ),
        migrations.AlterField(
            model_name='allowableservice',
            name='ServiceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Service_Associated_to_Allowed_Service', to='FightScheduler.Service', verbose_name='Service Associated to Allowed Service'),
        ),
        migrations.AlterField(
            model_name='match',
            name='blueBoxerUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Blue_Corner_Boxer', to=settings.AUTH_USER_MODEL, verbose_name='Blue Corner Boxer'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cornerJudge1Ruling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Corner_Judge_1_Winner_Pick_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 1 Winner Pick User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cornerJudge1UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Corner_Judge_1_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 1 User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cornerJudge2Ruling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Corner_Judge_2_Winner_Pick_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 2 Winner Pick User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cornerJudge2UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Corner_Judge_2_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 2 User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cornerJudge3Ruling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Corner_Judge_3_Winner_Pick_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 3 Winner Pick User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cornerJudge3UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Corner_Judge_3_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 3 User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cornerJudge4Ruling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Corner_Judge_4_Winner_Pick_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 4 Winner Pick User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cornerJudge4UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Corner_Judge_4_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Corner Judge 4 User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchResultCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Match_Result_Code', to='FightScheduler.MatchResultCode', verbose_name='Match Result Code'),
        ),
        migrations.AlterField(
            model_name='match',
            name='redBoxerUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Red_Corner_Boxer', to=settings.AUTH_USER_MODEL, verbose_name='Red Corner Boxer'),
        ),
        migrations.AlterField(
            model_name='match',
            name='refereeRuling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Referee_Winner_Pick_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Referee Winner Pick User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='refereeUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Referee_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Referee User ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winnerUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Winning_Boxer_UserID', to=settings.AUTH_USER_MODEL, verbose_name='Winning Boxer UserID'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='matchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Match_ID', to='FightScheduler.Match', verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='medicalcert',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Medical_Cert_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Medical Cert User ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='clubCoachUserID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Club_Coach_User', to=settings.AUTH_USER_MODEL, verbose_name='Club Coach User'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='clubOwnerUserID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Club_Owner_User', to=settings.AUTH_USER_MODEL, verbose_name='Club Owner User'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='clubPresidentUserID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='President_User', to=settings.AUTH_USER_MODEL, verbose_name='President User'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mailingAddressID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Mailing_Address_of_Organization', to='FightScheduler.Address', verbose_name='Mailing Address of Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='physicalAddressID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Physical_Address_of_Organization', to='FightScheduler.Address', verbose_name='Physical Address of Organization'),
        ),
        migrations.AlterField(
            model_name='person',
            name='accountTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Person_Account_Type', to='FightScheduler.AccountType', verbose_name='Person Account Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='statusCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Person_System_Status', to='FightScheduler.StatusCode', verbose_name='Person System Status'),
        ),
        migrations.AlterField(
            model_name='series',
            name='organizationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Organization_ID', to='FightScheduler.Organization', verbose_name='Organization ID'),
        ),
        migrations.AlterField(
            model_name='serviceenrollment',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Enrolled_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='Enrolled User ID'),
        ),
        migrations.AlterField(
            model_name='serviceenrollment',
            name='serviceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Service_ID', to='FightScheduler.Service', verbose_name='Service ID'),
        ),
        migrations.AlterField(
            model_name='show',
            name='addressID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Show_Venue', to='FightScheduler.Address', verbose_name='Show Venue'),
        ),
        migrations.AlterField(
            model_name='show',
            name='organizingOrganizationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Organizing_Organization_ID', to='FightScheduler.Organization', verbose_name='Organizing Organization ID'),
        ),
        migrations.AlterField(
            model_name='show',
            name='seriesID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Series_ID', to='FightScheduler.Series', verbose_name='Series ID'),
        ),
        migrations.AlterField(
            model_name='signedwaiver',
            name='signatoryUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Signatory_on_Behalf_Of', to=settings.AUTH_USER_MODEL, verbose_name='Signatory on Behalf Of'),
        ),
        migrations.AlterField(
            model_name='signedwaiver',
            name='signatureID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Signature_ID', to='FightScheduler.Signature', verbose_name='Signature ID'),
        ),
        migrations.AlterField(
            model_name='signedwaiver',
            name='waiverFormUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Waiver_Form_User', to=settings.AUTH_USER_MODEL, verbose_name='Waiver Form User'),
        ),
    ]
