# Generated by Django 3.0.8 on 2020-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0019_auto_20200722_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='isBoxer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='additionalInsurees',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='clubEmailRecipients',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='clubMailRecipients',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organizationShortName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
