# Generated by Django 3.0.8 on 2020-07-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0020_auto_20200722_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='dateofBirth',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='genderCode',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='height',
        ),
        migrations.AddField(
            model_name='career',
            name='boxerType',
            field=models.CharField(choices=[('AD', 'Adult Boxer'), ('JR', 'Junior Boxer'), ('NO', 'Not a Boxer')], default='AD', max_length=2),
        ),
        migrations.AddField(
            model_name='career',
            name='dateofBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='genderCode',
            field=models.CharField(choices=[('Male', 'Male Category'), ('Female', 'Female Category'), ('Other', 'Other Category')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='career',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='boxerType',
            field=models.CharField(max_length=20),
        ),
    ]
