# Generated by Django 3.0.8 on 2020-07-23 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0021_auto_20200722_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInvitationCode',
            fields=[
                ('AdminInvitationCodeID', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('used', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='nonboxerinfo',
            name='boxingOntarioAdminInvitationCode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nonboxerinfo',
            name='clubOwnership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Club_of_Owner', to='FightScheduler.Organization', verbose_name='Club of the Owner'),
        ),
        migrations.AddField(
            model_name='nonboxerinfo',
            name='clubOwnershipProofDocument',
            field=models.BinaryField(max_length=5000000, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='genderCode',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='coachLevel',
            field=models.CharField(choices=[('1', 'Certified Apprentice Coach'), ('2', 'Certified Club Coach'), ('3', 'Competition Coach'), ('4', 'Advanced Coaching Diploma'), ('5', 'Advanced Coaching Diploma II')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='nccpNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='officialLevel',
            field=models.CharField(choices=[('1', 'Regional I'), ('2', 'Regional II'), ('3', 'Provincial'), ('4', 'National')], default='1', max_length=30),
        ),
    ]
