# Generated by Django 3.0.8 on 2020-07-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0023_auto_20200722_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonboxerinfo',
            old_name='boxingOntarionEmployeeNum',
            new_name='boxingOntarioEmployeeNum',
        ),
    ]
