# Generated by Django 3.0.8 on 2020-07-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0025_accountinfo_registrationcomplete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='boxerType',
        ),
    ]
