# Generated by Django 3.0.8 on 2020-07-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0026_remove_career_boxertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='previousAmateurCombatSportInvolvement',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousCombatSportInvolvementInOtherCountry',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
