# Generated by Django 3.0.8 on 2020-07-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0027_auto_20200723_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='boxerType',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
