# Generated by Django 3.0.8 on 2020-07-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0029_auto_20200725_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='coachLevel',
            field=models.CharField(choices=[('1', '1 - Certified Apprentice Coach'), ('2', '2 - Certified Club Coach'), ('3', '3 - Competition Coach'), ('4', '4 - Advanced Coaching Diploma I'), ('5', '5 - Advanced Coaching Diploma II')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='officialLevel',
            field=models.CharField(choices=[('1', '1 - Regional I'), ('2', '2 - Regional II'), ('3', '3 - Provincial'), ('4', '4 - National')], max_length=30, null=True),
        ),
    ]
