# Generated by Django 3.0.8 on 2020-07-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0031_auto_20200725_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='clubOwnershipProofDocument',
            field=models.FileField(null=True, upload_to='.'),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='policeRecordsCheckExpiry',
            field=models.DateField(null=True),
        ),
    ]
