# Generated by Django 3.0.8 on 2020-07-27 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FightScheduler', '0032_auto_20200725_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_ID_for_Accopunt_Info', to=settings.AUTH_USER_MODEL, verbose_name='User ID for Account Info'),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='clubOwnershipProofDocument',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
