# Generated by Django 3.0.8 on 2020-07-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0033_auto_20200727_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='isJudgeOnly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchResultCode',
            field=models.CharField(choices=[('KO', 'Knock Out'), ('TKO', 'Technical Knock Out'), ('UD', 'Unanimous Decision'), ('SD', 'Split Decision'), ('MD', 'Majority Decision'), ('DR', 'Draw')], max_length=20),
        ),
    ]
