# Generated by Django 3.0.8 on 2020-07-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightScheduler', '0035_remove_match_refereeruling'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
