# Generated by Django 3.0.8 on 2020-07-31 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FightScheduler', '0036_match_matchnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callToConfirmAvailability', models.BooleanField()),
                ('sundayAMAvailability', models.BooleanField()),
                ('mondayAMAvailability', models.BooleanField()),
                ('tuesdayAMAvailability', models.BooleanField()),
                ('wednesdayAMAvailability', models.BooleanField()),
                ('thursdayAMAvailability', models.BooleanField()),
                ('fridayAMAvailability', models.BooleanField()),
                ('saturdayAMAvailability', models.BooleanField()),
                ('sundayPMAvailability', models.BooleanField()),
                ('mondayPMAvailability', models.BooleanField()),
                ('tuesdayPMAvailability', models.BooleanField()),
                ('wednesdayPMAvailability', models.BooleanField()),
                ('thursdayPMAvailability', models.BooleanField()),
                ('fridayPMAvailability', models.BooleanField()),
                ('saturdayPMAvailability', models.BooleanField()),
                ('availableJanuary', models.BooleanField()),
                ('availableFebruary', models.BooleanField()),
                ('availableMarch', models.BooleanField()),
                ('availableApril', models.BooleanField()),
                ('availableMay', models.BooleanField()),
                ('availableJune', models.BooleanField()),
                ('availableJuly', models.BooleanField()),
                ('availableAugust', models.BooleanField()),
                ('availableSeptember', models.BooleanField()),
                ('availableOctober', models.BooleanField()),
                ('availableNovember', models.BooleanField()),
                ('availableDecember', models.BooleanField()),
                ('createdOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastModified', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_Availability', to=settings.AUTH_USER_MODEL, verbose_name='User Availability')),
            ],
        ),
    ]
