# Generated by Django 3.0.8 on 2020-08-04 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FightScheduler', '0037_availabilityschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='boxerType',
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_ID_for_Account_Info', to=settings.AUTH_USER_MODEL, verbose_name='User ID for Account Info'),
        ),
        migrations.AlterField(
            model_name='availabilityschedule',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_for_Availability_Schedule', to=settings.AUTH_USER_MODEL, verbose_name='User for Availability Schedule'),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousAmateurCombatSportInvolvement',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='previousCombatSportInvolvementInOtherCountry',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchResultCode',
            field=models.CharField(choices=[('KO', 'Knock Out'), ('TKO', 'Technical Knock Out'), ('UD', 'Unanimous Decision'), ('SD', 'Split Decision'), ('MD', 'Majority Decision'), ('DR', 'Draw')], max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalcert',
            name='image',
            field=models.FileField(max_length=5000000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='clubOwnershipProofDocument',
            field=models.FileField(max_length=5000000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='coachLevel',
            field=models.CharField(choices=[('1', '1 - Certified Apprentice Coach'), ('2', '2 - Certified Club Coach'), ('3', '3 - Competition Coach'), ('4', '4 - Advanced Coaching Diploma I'), ('5', '5 - Advanced Coaching Diploma II')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='nonboxerinfo',
            name='officialLevel',
            field=models.CharField(choices=[('1', '1 - Regional I'), ('2', '2 - Regional II'), ('3', '3 - Provincial'), ('4', '4 - National')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.FileField(max_length=5000000, upload_to=''),
        ),
    ]
